-- ---------------------------------------------------------------------------
-- Add Drive-backed albums to an existing database.
--
-- This now lives as a migration so `supabase db push` can apply it:
--
--     supabase link --project-ref <your-project-ref>
--     supabase db push
--
-- See supabase/migrations/20260101000000_work_albums.sql for the SQL. It stays
-- idempotent, so running it by hand in the SQL Editor is still fine.
--
-- It touches only work_albums and work_album_media, so work_projects and every
-- other existing table are left alone.
-- ---------------------------------------------------------------------------
